# Generated by Django 5.2.6 on 2025-10-03 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0002_exam_description_question_explanation_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='exam',
            name='password',
            field=models.CharField(default=1, help_text='Password required for students to access this exam', max_length=255),
            preserve_default=False,
        ),
    ]
