# Generated by Django 5.2.6 on 2025-09-29 10:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('exam_sessions', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Violation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('violation_type', models.CharField(choices=[('MULTIPLE_FACES', 'Multiple Faces'), ('TAB_SWITCH', 'Tab Switch'), ('LOOKING_AWAY', 'Looking Away'), ('COPY_PASTE', 'Copy/Paste'), ('HEAD_MOVEMENT', 'Head Movement'), ('OTHER', 'Other')], max_length=32)),
                ('timestamp', models.DateTimeField()),
                ('details', models.CharField(blank=True, default='', max_length=512)),
                ('resolved', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='violations', to='exam_sessions.examsession')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='violations', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
